import os
import json

ROOT = "songs"
OUTPUT = "files.js"

songs = []

if os.path.exists(ROOT):
    for file in sorted(os.listdir(ROOT)):
        if file.lower().endswith(".mjk"):
            songs.append(f"{ROOT}/{file}")

with open(OUTPUT, "w", encoding="utf-8") as f:
    f.write("// Auto-generated by generate_files.py\n")
    f.write("// Do not edit manually.\n\n")
    f.write("window.MYUJIKKU_FILES = ")
    json.dump(
        {
            "songs": songs
        },
        f,
        indent=2,
        ensure_ascii=False
    )
    f.write(";\n")

print(f"Generated {len(songs)} songs")